language: python
python:
  - 2.7
install:
  - python setup.py install 
  - python -m tests.test_client 
script: python setup.py test
notifications:
    email: 
      recipients:
        - mjdorma+travis-ci@gmail.com
        - sptonkin@outlook.com
      on_success: change
      on_failure: always
