language: python
python:
  - 2.7
install:
  - python setup.py install 
  - pip install webtest
  - python -m tests.test_client 
script: 
  - coverage run setup.py test
  - coverage report --show-missing
notifications:
    email: 
      recipients:
        - mjdorma+travis-ci@gmail.com
        - sptonkin@outlook.com
      on_success: change
      on_failure: always
