language: python
python:
  - 2.7
  - 3.2
install:
  - python setup.py install 
script: python setup.py test
notifications:
    email: 
      recipients:
        - mjdorma+travis-ci@gmail.com
        - sptonkin@outlook.com
      on_success: change
      on_failure: always
